language: python
python:
    - 3.4.3
install:
    - pip install -r requirements.txt
script: python manage.py test
branches:
    only:
        - master
before_install:
  - pip install codecov
after_success:
  - codecov
repo_token: 9p7lic2B1H0hjwIGC1EoSrwvSRpcd8wuw
