language: python
python:
    - 3.4.3
install:
    - pip install -r requirements/testing.txt
script: python manage.py test
branches:
    only:
        - master
before_install:
  - pip install codecov
after_success:
  - codecov
